### ISSUE TITLE
和https://github.com/snowdrop/istio-java-api这个啥区别哇？

### ISSUE THREAD

**Issue by victory460** [llarao/istio-java#4]
当时是觉得https://github.com/snowdrop/istio-java-api 这个不好用，所以大佬自己造了一个轮子吗？

**Comment by llarao** [comment]
那个改的更彻底一些，这个只是基于fabric基础上扩展了CRD资源。（ps：写这个也是想稍微看看源码，没有大佬们改的彻底）
